name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild build -project PanCredCard/PanCredCard.xcodeproj -scheme PanCredCard clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
      - name: Run tests
        run: xcodebuild test -project PanCredCard/PanCredCard.xcodeproj -scheme PanCredCard clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No

